--task5 
-- THIS IS INNER JOIN, IN THIS QUERY WE HAVE JOINED THE STUDENT AND DEPARTMENT_INFO USING THE COMMON COLUMN PRESENT IN BOTH TABLES THAT IS DEPARTMENT

SELECT S.S_NAME, S.DEPARTMENT, D.HOD_NAME
FROM STUDENT S
INNER JOIN DEPARTMENT_INFO D ON S.DEPARTMENT = D.DEPARTMENT;

-- THIS IS LEFT JOIN, IT RETURNS ALL RECORDS FROM THE STUDENT TABLE AND THE MATCHING RECORDS FROM DEPARTMENT_INFO.
-- IF THERE IS NO MATCH, THE DEPARTMENT_INFO COLUMNS WILL CONTAIN NULL.

SELECT S.S_NAME, S.DEPARTMENT, D.HOD_NAME
FROM STUDENT S
LEFT JOIN DEPARTMENT_INFO D ON S.DEPARTMENT = D.DEPARTMENT;

-- THIS IS RIGHT JOIN, IT RETURNS ALL RECORDS FROM THE DEPARTMENT_INFO TABLE AND THE MATCHING RECORDS FROM STUDENT.
-- IF THERE IS NO MATCH, THE STUDENT COLUMNS WILL CONTAIN NULL.

SELECT S.S_NAME, S.DEPARTMENT, D.HOD_NAME
FROM STUDENT S
RIGHT JOIN DEPARTMENT_INFO D ON S.DEPARTMENT = D.DEPARTMENT;

-- THIS IS FULL OUTER JOIN, IT RETURNS ALL RECORDS WHEN THERE IS A MATCH IN EITHER STUDENT OR DEPARTMENT_INFO TABLE.
-- IF THERE IS NO MATCH, THE MISSING SIDE WILL HAVE NULL VALUES.

SELECT S.S_NAME, S.DEPARTMENT AS STUDENT_DEPT, D.DEPARTMENT AS DEPT_NAME, D.HOD_NAME
FROM STUDENT S
FULL OUTER JOIN DEPARTMENT_INFO D ON S.DEPARTMENT = D.DEPARTMENT;
